Name:Rushi Rvairaj Gujarathi ||Roll no-17 ||PRN NO-1252090017

Assingment no:1

Perform the following operations using Python on suitable data sets:

1.Read data from different formats (like csv, xls)

2.Find Shape of Data Find Missing Values

3.Find data type of each column

4.Finding out Zero's

5.Indexing and selecting data, sort data,

6.Describe attributes of data, checking data types of each column,

7.counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

# 1.Read data from different formats (like csv, xls)

In [ ]:
import pandas as pd
import numpy as np

Reading the content of  House Price Prediction Dataset.

In [ ]:
df=pd.read_csv("/content/House Price Prediction Dataset.csv")
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

  Reading the content of Excel File

In [ ]:
df=pd.read_excel("/content/data.xlsx")
df.head()

   Name   Age  Salary    City
0  Amit  22.0   25000    Pune
1  Ravi   0.0   30000  Mumbai
2  Sita  25.0       0    Pune
3  Neha   NaN   40000   Delhi
4  Ravi  22.0   30000    Pune

# Assingment ans
2.Find Shape of Data

3.Find Missing Values

4.Find data type of each column

5.Finding out Zero's

6.Indexing and selecting data, sort data,

7.Describe attributes of data, checking data types of each column,

8.counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

In [ ]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Rushi', 'Ravi', 'Sita', 'Neha', 'Rahul'],
    'age': [20, 21, 22, 20, 23],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
    'department': ['CS', 'IT', 'CS', 'ENTC', 'MECH'],
    'marks': [78, 85, 0, 92, 88],
    'attendance': [90, 75, 80, 95, 0],
    'internship': ['Yes', 'No', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)

def gap():
  print("\n" + "-"*50 + "\n")

print("1) Shape of Data (Rows, Columns)")
print(df.shape)
gap()


print("2) Missing Values in each column")
print(df.isnull().sum())
gap()


print("3) Data Types of each column")
print(df.dtypes)
gap()


print("4) Zero values in each column")
print((df == 0).sum())
gap()


print("5) Indexing & Selecting Data")

print("\n-- Name Column --")
print(df['name'])

print("\n-- First 3 Rows --")
print(df.iloc[0:3])

print("\n-- Students with Marks > 80 --")
print(df[df['marks'] > 80])
gap()


print("6) Sorting Data by Marks (Descending)")
print(df.sort_values(by='marks', ascending=False))
gap()

print("6) Sorting Data by Marks (Aescending)")
print(df.sort_values(by='marks', ascending=True))
gap()

print("7) Describe Data")
print(df.describe())
gap()


print("8) DataFrame Info")
df.info()
gap()


print("9) Unique values count in each column")
print(df.nunique())
gap()


print("10) Average Marks Department wise")
print(df.groupby('department')['marks'].mean())
gap()


print("11) Data Type Conversion")

df['student_id'] = df['student_id'].astype(str)
df['marks'] = df['marks'].astype(float)
df['internship'] = df['internship'].map({'Yes': True, 'No': False})

print(df.dtypes)
gap()


print("12) Convert String Columns to Lowercase")
df = df.apply(lambda col: col.str.lower() if col.dtype == 'object' else col)
print(df)
gap()

print(" ALL OPERATIONS COMPLETED SUCCESSFULLY")

1) Shape of Data (Rows, Columns)
(5, 8)

--------------------------------------------------

2) Missing Values in each column
student_id    0
name          0
age           0
gender        0
department    0
marks         0
attendance    0
internship    0
dtype: int64

--------------------------------------------------

3) Data Types of each column
student_id     int64
name          object
age            int64
gender        object
department    object
marks          int64
attendance     int64
internship    object
dtype: object

--------------------------------------------------

4) Zero values in each column
student_id    0
name          0
age           0
gender        0
department    0
marks         1
attendance    1
internship    0
dtype: int64

--------------------------------------------------

5) Indexing & Selecting Data

-- Name Column --
0    Rushi
1     Ravi
2     Sita
3     Neha
4    Rahul
Name: name, dtype: object

-- First 3 Rows --
   student_id   name  age  gender department  marks  attendance internship
0         101  Rushi   20    Male         CS     78          90        Yes
1         102   Ravi   21    Male         IT     85          75         No
2         103   Sita   22  Female         CS      0          80        Yes

-- Students with Marks > 80 --
   student_id   name  age  gender department  marks  attendance internship
1         102   Ravi   21    Male         IT     85          75         No
3         104   Neha   20  Female       ENTC     92          95        Yes
4         105  Rahul   23    Male       MECH     88           0         No

--------------------------------------------------

6) Sorting Data by Marks (Descending)
   student_id   name  age  gender department  marks  attendance internship
3         104   Neha   20  Female       ENTC     92          95        Yes
4         105  Rahul   23    Male       MECH     88           0         No
1         102   Ravi   21    Male         IT     85          75         No
0         101  Rushi   20    Male         CS     78          90        Yes
2         103   Sita   22  Female         CS      0          80        Yes

--------------------------------------------------

6) Sorting Data by Marks (Aescending)
   student_id   name  age  gender department  marks  attendance internship
2         103   Sita   22  Female         CS      0          80        Yes
0         101  Rushi   20    Male         CS     78          90        Yes
1         102   Ravi   21    Male         IT     85          75         No
4         105  Rahul   23    Male       MECH     88           0         No
3         104   Neha   20  Female       ENTC     92          95        Yes

--------------------------------------------------

7) Describe Data
       student_id       age    marks  attendance
count    5.000000   5.00000   5.0000    5.000000
mean   103.000000  21.20000  68.6000   68.000000
std      1.581139   1.30384  38.6885   38.826537
min    101.000000  20.00000   0.0000    0.000000
25%    102.000000  20.00000  78.0000   75.000000
50%    103.000000  21.00000  85.0000   80.000000
75%    104.000000  22.00000  88.0000   90.000000
max    105.000000  23.00000  92.0000   95.000000

--------------------------------------------------

8) DataFrame Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  5 non-null      int64
 1   name        5 non-null      object
 2   age         5 non-null      int64
 3   gender      5 non-null      object
 4   department  5 non-null      object
 5   marks       5 non-null      int64
 6   attendance  5 non-null      int64
 7   internship  5 non-null      object
dtypes: int64(4), object(4)
memory usage: 452.0+ bytes

--------------------------------------------------

9) Unique values count in each column
student_id    5
name          5
age           4
gender        2
department    4
marks         5
attendance    5
internship    2
dtype: int64

--------------------------------------------------

10) Average Marks Department wise
department
CS      39.0
ENTC    92.0
IT      85.0
MECH    88.0
Name: marks, dtype: float64

--------------------------------------------------

11) Data Type Conversion
student_id     object
name           object
age             int64
gender         object
department     object
marks         float64
attendance      int64
internship       bool
dtype: object

--------------------------------------------------

12) Convert String Columns to Lowercase
  student_id   name  age  gender department  marks  attendance  internship
0        101  rushi   20    male         cs   78.0          90        True
1        102   ravi   21    male         it   85.0          75       False
2        103   sita   22  female         cs    0.0          80        True
3        104   neha   20  female       entc   92.0          95        True
4        105  rahul   23    male       mech   88.0           0       False

--------------------------------------------------

 ALL OPERATIONS COMPLETED SUCCESSFULLY

# Practice:10 minutes to pandas
# Basic data structures in pandas


*  Series: a one-dimensional labeled array holding data of any type
          such as integers, strings, Python objects etc.
* DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

1. Series

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

2. DataFrame

In [ ]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Rushi', 'Ravi', 'Sita', 'Neha', 'Rahul'],
    'age': [20, 21, 22, 20, 23],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
    'department': ['CS', 'IT', 'CS', 'ENTC', 'MECH'],
    'marks': [78, 85, 0, 92, 88],
    'attendance': [90, 75, 80, 95, 0],
    'internship': ['Yes', 'No', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)
df

   student_id   name  age  gender department  marks  attendance internship
0         101  Rushi   20    Male         CS     78          90        Yes
1         102   Ravi   21    Male         IT     85          75         No
2         103   Sita   22  Female         CS      0          80        Yes
3         104   Neha   20  Female       ENTC     92          95        Yes
4         105  Rahul   23    Male       MECH     88           0         No

different dtypes: The columns of the resulting DataFrame have different dtypes

In [ ]:
df.dtypes

student_id     int64
name          object
age            int64
gender        object
department    object
marks          int64
attendance     int64
internship    object
dtype: object

Viewing data

Use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:

In [ ]:
df.head(2)

   student_id   name  age gender department  marks  attendance internship
0         101  Rushi   20   Male         CS     78          90        Yes
1         102   Ravi   21   Male         IT     85          75         No

In [ ]:
df.tail(2)

   student_id   name  age  gender department  marks  attendance internship
3         104   Neha   20  Female       ENTC     92          95        Yes
4         105  Rahul   23    Male       MECH     88           0         No

Display the DataFrame.index

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

Display the DataFrame.columns:

In [ ]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'department', 'marks',
       'attendance', 'internship'],
      dtype='object')

Return a NumPy representation of the underlying data with DataFrame.to_numpy() without the index or column labels:

In [ ]:
df.to_numpy()

array([[101, 'Rushi', 20, 'Male', 'CS', 78, 90, 'Yes'],
       [102, 'Ravi', 21, 'Male', 'IT', 85, 75, 'No'],
       [103, 'Sita', 22, 'Female', 'CS', 0, 80, 'Yes'],
       [104, 'Neha', 20, 'Female', 'ENTC', 92, 95, 'Yes'],
       [105, 'Rahul', 23, 'Male', 'MECH', 88, 0, 'No']], dtype=object)

describe() shows a quick statistic summary of your data:

In [ ]:
df.describe()

       student_id       age    marks  attendance
count    5.000000   5.00000   5.0000    5.000000
mean   103.000000  21.20000  68.6000   68.000000
std      1.581139   1.30384  38.6885   38.826537
min    101.000000  20.00000   0.0000    0.000000
25%    102.000000  20.00000  78.0000   75.000000
50%    103.000000  21.00000  85.0000   80.000000
75%    104.000000  22.00000  88.0000   90.000000
max    105.000000  23.00000  92.0000   95.000000

DataFrame.sort_index() sorts by an axis:

In [ ]:
df.sort_index(axis=1)

   age  attendance department  gender internship  marks   name  student_id
0   20          90         CS    Male        Yes     78  Rushi         101
1   21          75         IT    Male         No     85   Ravi         102
2   22          80         CS  Female        Yes      0   Sita         103
3   20          95       ENTC  Female        Yes     92   Neha         104
4   23           0       MECH    Male         No     88  Rahul         105

DataFrame.sort_values() sorts by values:

In [ ]:
df.sort_values(by='age')

   student_id   name  age  gender department  marks  attendance internship
0         101  Rushi   20    Male         CS     78          90        Yes
3         104   Neha   20  Female       ENTC     92          95        Yes
1         102   Ravi   21    Male         IT     85          75         No
2         103   Sita   22  Female         CS      0          80        Yes
4         105  Rahul   23    Male       MECH     88           0         No

# **Selection**

Getitem ([])
For a DataFrame, passing a single label selects a columns and yields a Series equivalent to df.A:

In [ ]:
import pandas as pd

data = { 'student_id': [101, 102, 103, 104, 105],
         'name': ['Rushi', 'Ravi', 'Sita', 'Neha', 'Rahul'],
          'age': [20, 21, 22, 20, 23],
          'gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
          'department': ['CS', 'IT', 'CS', 'ENTC', 'MECH'],
          'marks': [78, 85, 0, 92, 88],
          'attendance': [90, 75, 80, 95, 0],
          'internship': ['Yes', 'No', 'Yes', 'Yes', 'No'] }
df = pd.DataFrame(data)
df["age"]

0    20
1    21
2    22
3    20
4    23
Name: age, dtype: int64

For a DataFrame, passing a slice : selects matching rows:

In [ ]:
df[0:2]

   student_id   name  age gender department  marks  attendance internship
0         101  Rushi   20   Male         CS     78          90        Yes
1         102   Ravi   21   Male         IT     85          75         No

# **Selection by label**
See more in Selection by Label using DataFrame.loc() or DataFrame.at().

Selecting a row matching a label:

In [ ]:
df.loc[0]

student_id      101
name          Rushi
age              20
gender         Male
department       CS
marks            78
attendance       90
internship      Yes
Name: 0, dtype: object

In [ ]:
df.loc[:,["age","student_id"]]

   age  student_id
0   20         101
1   21         102
2   22         103
3   20         104
4   23         105

# **Selection by position**
See more in Selection by Position using DataFrame.iloc() or DataFrame.iat().

Select via the position of the passed integers:

In [ ]:
df.iloc[3]

student_id       104
name            Neha
age               20
gender        Female
department      ENTC
marks             92
attendance        95
internship       Yes
Name: 3, dtype: object

In [ ]:
df.iloc[3:5, 0:2]

   student_id   name
3         104   Neha
4         105  Rahul

# Boolean indexing
Select rows where df.A is greater than 0.

In [ ]:

df[df["age"] > 20]

   student_id   name  age  gender department  marks  attendance internship
1         102   Ravi   21    Male         IT     85          75         No
2         103   Sita   22  Female         CS      0          80        Yes
4         105  Rahul   23    Male       MECH     88           0         No

# Setting
Setting a new column automatically aligns the data by the indexes:

In [ ]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

data = {
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Rushi', 'Ravi', 'Sita', 'Neha', 'Rahul'],
    'age': [20, 21, 22, 20, 23],
    'gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
    'department': ['CS', 'IT', 'CS', 'ENTC', 'MECH'],
    'marks': [78, 85, 0, 92, 88],
    'attendance': [90, 75, 80, 95, 0],
    'internship': ['Yes', 'No', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)

df["F"] = s1
print(df)

   student_id   name  age  gender department  marks  attendance internship   F
0         101  Rushi   20    Male         CS     78          90        Yes NaN
1         102   Ravi   21    Male         IT     85          75         No NaN
2         103   Sita   22  Female         CS      0          80        Yes NaN
3         104   Neha   20  Female       ENTC     92          95        Yes NaN
4         105  Rahul   23    Male       MECH     88           0         No NaN

# **Operations**

Operations in general exclude missing data.

Calculate the mean value for each column:

In [ ]:
df[['age', 'marks', 'attendance']].mean()

age           21.2
marks         68.6
attendance    68.0
dtype: float64

# Merge:
pandas provides various facilities for easily combining together Series and DataFrame objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

See the Merging section.

Concatenating pandas objects together row-wise with concat():

In [ ]:
import pandas as pd

df1 = df.iloc[0:3]   # first 3 rows
df2 = df.iloc[3:5]   # last 2 rows

result = pd.concat([df1, df2])
print(result)

   student_id   name  age  gender department  marks  attendance internship
0         101  rushi   20    male         cs     78          90        yes
1         102   ravi   21    male         it     85          75         no
2         103   sita   22  female         cs      0          80        yes
3         104   neha   20  female       entc     92          95        yes
4         105  rahul   23    male       mech     88           0         no

# **Join**
merge() enables SQL style join types along specific columns. See the Database style joining section.

In [ ]:
extra = pd.DataFrame({
    'sports': ['Cricket', 'Football', 'Chess', 'Tennis', 'Hockey']
}, index=df.index)

result = df.join(extra)
print(result)

   student_id   name  age  gender department  marks  attendance internship  \
0         101  rushi   20    male         cs     78          90        yes
1         102   ravi   21    male         it     85          75         no
2         103   sita   22  female         cs      0          80        yes
3         104   neha   20  female       entc     92          95        yes
4         105  rahul   23    male       mech     88           0         no

     sports
0   Cricket
1  Football
2     Chess
3    Tennis
4    Hockey

# **Grouping**
By “group by” we are referring to a process involving one or more of the following steps:

Splitting the data into groups based on some criteria

Applying a function to each group independently

Combining the results into a data structure

In [ ]:
df.groupby('department')['marks'].mean()

department
cs      39.0
entc    92.0
it      85.0
mech    88.0
Name: marks, dtype: float64